name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: checkout submodule
      run: git submodule sync --recursive && git submodule update --init --recursive
      
    
